-- ============================================================================
-- Seed: 276 more globally-applicable debate questions (PL + EN) + 2 smaczki each
-- ----------------------------------------------------------------------------
-- Generated 2026-06-27. Third large batch of YES/NO ("TAK/NIE") questions,
-- following the same recipe as 20260625130000_seed_global_dilemmas_batch.sql and
-- 20260627120000_seed_global_dilemmas_batch_2.sql. This batch brings the active
-- catalog to ~500 questions total.
--
-- Every question is deliberately GLOBAL: a universal values/life dilemma a person
-- in any country (Poland, USA, anywhere) can debate. No country-, law-, currency-
-- or institution-specific framings.
--
-- Tuned to be CONTROVERSIAL BUT BALANCED -- chosen to split people close to
-- ~50/50, NOT lopsided "obvious" questions. Spread across love/dating/friendship,
-- parenting/education, money/work, technology/AI, health/body/lifestyle, and
-- ethics/justice/meaning.
--
-- Each question gets exactly TWO "smaczki" (discussion angles), bilingual:
--   position 1 -> shown FREE (strongest hook)
--   position 2 -> premium-gated
-- This matches the product cap of max two smaczki per question
-- (see 20260623120000_trim_smaczki_to_max_two.sql) and the get_question_smaczki
-- RPC gating (position 1 free, rest premium).
--
-- Idempotent: each question is keyed on its EN text, so re-running skips rows
-- that already exist (no duplicate translations or smaczki). One row at a time
-- so the freshly generated ids map to the right PL/EN pair and smaczki.
-- ============================================================================

begin;

-- ----------------------------------------------------------------------------
-- 1) Insert each question + both translations + its two bilingual smaczki.
-- ----------------------------------------------------------------------------
do $$
declare
  r   record;
  qid uuid;
  s1  uuid;
  s2  uuid;
begin
  for r in
    select * from (values
      -- ---------------- Love, dating, sex & friendship ----------------
      ('Relationships', false,
       'Is it okay to use heavily edited photos on a dating profile?',
       'Czy wolno wrzucać mocno podrasowane zdjęcia na profilu randkowym?',
       'Just my best self?', 'Tylko lepsza wersja?',
       'Or catfishing?', 'Czy oszustwo?'),
      ('Relationships', true,
       'Should you tell a new partner exactly how many people you''ve slept with?',
       'Czy powinieneś mówić nowemu partnerowi, z iloma osobami spałeś?',
       'Need to know?', 'Musi wiedzieć?',
       'Past stays past?', 'Przeszłość to przeszłość?'),
      ('Relationships', false,
       'Is it okay to date several people at once before things get serious?',
       'Czy wolno spotykać się z kilkoma osobami naraz, zanim zrobi się poważnie?',
       'Keeping options open?', 'Trzymasz opcje otwarte?',
       'Or just dishonest?', 'Czy nieuczciwe?'),
      ('Relationships', false,
       'Should whoever asked for the date always pay the bill?',
       'Czy ten, kto zaprosił na randkę, powinien zawsze zapłacić rachunek?',
       'You invite, you pay?', 'Zapraszasz, płacisz?',
       'Split like equals?', 'Po równo, jak równi?'),
      ('Relationships', true,
       'Should you check a date''s social media before meeting them?',
       'Czy powinieneś sprawdzić media społecznościowe randki przed spotkaniem?',
       'Safety first?', 'Najpierw bezpieczeństwo?',
       'Snooping already?', 'Już węszysz?'),
      ('Relationships', false,
       'Is it okay to ghost someone after a few dates instead of explaining?',
       'Czy wolno zniknąć komuś po kilku randkach zamiast się wytłumaczyć?',
       'Less drama?', 'Mniej dramy?',
       'They deserve a word?', 'Należy się słowo?'),
      ('Relationships', true,
       'Should you wait several dates before sleeping together?',
       'Czy powinieneś poczekać kilka randek przed pójściem do łóżka?',
       'Worth the wait?', 'Warto poczekać?',
       'Why play games?', 'Po co te gierki?'),
      ('Relationships', false,
       'Should you be the first to say you love someone without knowing if they feel the same?',
       'Czy powinieneś pierwszy wyznać miłość, nie wiedząc, czy jest odwzajemniona?',
       'Brave heart?', 'Odważne serce?',
       'Too much, too soon?', 'Za dużo, za szybko?'),
      ('Relationships', true,
       'Can a relationship with no labels ever be fair to both people?',
       'Czy związek bez etykiet może być uczciwy dla obojga?',
       'Free of pressure?', 'Wolne od presji?',
       'One waits forever?', 'Ktoś czeka wiecznie?'),
      ('Relationships', false,
       'Is it a red flag if someone stays close with all their exes?',
       'Czy to niepokojący sygnał, gdy ktoś trzyma bliski kontakt ze wszystkimi byłymi?',
       'Mature and kind?', 'Dojrzały i miły?',
       'Door left open?', 'Drzwi uchylone?'),
      ('Relationships', false,
       'Is it wrong to stay in regular contact with an ex while in a new relationship?',
       'Czy to złe utrzymywać stały kontakt z byłym, będąc w nowym związku?',
       'Just old friends?', 'Po prostu znajomi?',
       'Playing with fire?', 'Igrasz z ogniem?'),
      ('Relationships', false,
       'Should you delete every photo of an ex once you''re with someone new?',
       'Czy powinieneś usunąć każde zdjęcie byłego, gdy jesteś już z kimś nowym?',
       'Fresh start?', 'Czysta karta?',
       'Erasing your story?', 'Wymazujesz historię?'),
      ('Relationships', true,
       'Is watching adult content a form of cheating on your partner?',
       'Czy oglądanie treści dla dorosłych to forma zdrady partnera?',
       'Eyes elsewhere?', 'Wzrok gdzie indziej?',
       'Harmless and private?', 'Niewinne i prywatne?'),
      ('Relationships', true,
       'Can an open relationship work as well as a faithful one?',
       'Czy otwarty związek może działać tak samo dobrze jak wierny?',
       'Honest about desire?', 'Szczerzy wobec pragnień?',
       'Jealousy always wins?', 'Zazdrość zawsze wygra?'),
      ('Relationships', false,
       'Is flirting with someone else while in a relationship already cheating?',
       'Czy flirt z kimś innym w trakcie związku to już zdrada?',
       'Crossing a line?', 'Przekraczasz granicę?',
       'Just harmless fun?', 'Niewinna zabawa?'),
      ('Relationships', true,
       'Should a couple with mismatched sex drives just compromise and move on?',
       'Czy para z różnym apetytem na seks powinna po prostu pójść na kompromis?',
       'Meet in the middle?', 'Spotkać się w pół drogi?',
       'Resentment grows?', 'Rośnie żal?'),
      ('Relationships', true,
       'Is it a betrayal to keep gifts from a past lover?',
       'Czy to zdrada trzymać prezenty od dawnej miłości?',
       'Just objects?', 'To tylko przedmioty?',
       'Ghost in the room?', 'Duch w pokoju?'),
      ('Relationships', false,
       'Should you tell your partner every detail of your romantic past?',
       'Czy powinieneś zdradzić partnerowi każdy szczegół swojej miłosnej przeszłości?',
       'Nothing to hide?', 'Nic do ukrycia?',
       'Some things stay buried?', 'Coś lepiej przemilczeć?'),
      ('Relationships', true,
       'Is it okay to be jealous of your partner''s close friend of the opposite sex?',
       'Czy wolno być zazdrosnym o bliskiego przyjaciela partnera płci przeciwnej?',
       'Gut feeling?', 'Przeczucie?',
       'Trust or control?', 'Zaufanie czy kontrola?'),
      ('Relationships', false,
       'Should exes who ended badly ever try getting back together?',
       'Czy byli, którzy rozstali się w złości, powinni próbować wrócić do siebie?',
       'Love deserves a retry?', 'Miłość warta drugiej próby?',
       'Same crash again?', 'Znów ten sam ból?'),
      ('Family', true,
       'Should couples live together before deciding to marry?',
       'Czy para powinna zamieszkać razem, zanim zdecyduje się na ślub?',
       'Test before vows?', 'Sprawdź przed ślubem?',
       'Kills the mystery?', 'Zabija tajemnicę?'),
      ('Family', false,
       'Is spending a fortune on a single wedding day ever worth it?',
       'Czy wydawanie fortuny na jeden dzień ślubu jest tego warte?',
       'Once in a lifetime?', 'Raz w życiu?',
       'A day for a house?', 'Dzień za cenę domu?'),
      ('Family', false,
       'Is it okay to ask wedding guests for cash instead of gifts?',
       'Czy wolno prosić gości weselnych o gotówkę zamiast prezentów?',
       'We know our needs?', 'Wiemy, czego nam trzeba?',
       'Charging for a seat?', 'Kasujesz za miejsce?'),
      ('Family', true,
       'Should couples be allowed to ban children from their wedding?',
       'Czy para powinna móc zakazać dzieciom wstępu na swój ślub?',
       'Adults'' night off?', 'Wieczór dla dorosłych?',
       'Family means everyone?', 'Rodzina to wszyscy?'),
      ('Relationships', false,
       'Should you attend the wedding of a friend you''ve drifted apart from?',
       'Czy powinieneś iść na ślub przyjaciela, z którym się oddaliłeś?',
       'Show up anyway?', 'Pojaw się mimo wszystko?',
       'Just an obligation?', 'Tylko obowiązek?'),
      ('Family', true,
       'Is it selfish to hold a far-off wedding guests must pay to reach?',
       'Czy to egoistyczne robić ślub na końcu świata, na który goście muszą sami dopłacić?',
       'Your dream day?', 'Twój wymarzony dzień?',
       'Their wallet bleeds?', 'Ich portfel płacze?'),
      ('Family', true,
       'Should one partner take the other''s family name after marriage?',
       'Czy jedno z partnerów powinno przyjąć nazwisko drugiego po ślubie?',
       'One united name?', 'Jedno wspólne nazwisko?',
       'Lose your identity?', 'Tracisz tożsamość?'),
      ('Relationships', false,
       'Is it a betrayal to start dating your friend''s ex?',
       'Czy to zdrada zacząć umawiać się z byłym przyjaciela?',
       'Heart wants who it wants?', 'Serce nie sługa?',
       'Breaks the code?', 'Łamiesz kodeks?'),
      ('Relationships', true,
       'Should you stay loyal to a friend who always cancels on you?',
       'Czy powinieneś być lojalny wobec przyjaciela, który ciągle cię wystawia?',
       'Everyone gets busy?', 'Każdy bywa zajęty?',
       'Always an excuse?', 'Zawsze wymówka?'),
      ('Relationships', false,
       'Is it okay to drop a friend who only calls when they need something?',
       'Czy wolno odpuścić przyjaciela, który odzywa się tylko, gdy czegoś potrzebuje?',
       'One-way street?', 'Ulica jednokierunkowa?',
       'Maybe they''re struggling?', 'Może z czymś walczy?'),
      ('Relationships', true,
       'Should you tell a friend you can''t stand their partner?',
       'Czy powinieneś powiedzieć przyjacielowi, że nie znosisz jego partnera?',
       'Better they hear it?', 'Lepiej, by usłyszał?',
       'Just push them away?', 'Tylko ich odepchniesz?'),
      ('Relationships', false,
       'Should you stay quiet while a friend keeps choosing toxic partners?',
       'Czy powinieneś milczeć, gdy przyjaciel wciąż wybiera toksycznych partnerów?',
       'Let them learn?', 'Niech się uczy?',
       'Silence helps no one?', 'Milczenie nie pomaga?'),
      ('Relationships', true,
       'Is it okay to keep a close friend your partner can''t stand?',
       'Czy wolno trzymać przy sobie bliskiego przyjaciela, którego partner nie znosi?',
       'Your life, your friends?', 'Twoje życie, twoi ludzie?',
       'Loyalty divided?', 'Lojalność rozdarta?'),
      ('Culture', false,
       'Is it rude to leave a party without saying goodbye to anyone?',
       'Czy to niegrzeczne wyjść z imprezy, nie żegnając się z nikim?',
       'Slip out quietly?', 'Wymknij się po cichu?',
       'Just bad manners?', 'Po prostu brak kultury?'),
      ('Relationships', false,
       'Should you always help a friend move house when they ask?',
       'Czy zawsze powinieneś pomóc przyjacielowi w przeprowadzce, gdy prosi?',
       'That''s what friends do?', 'Od tego są przyjaciele?',
       'Weekend gone?', 'Weekend w plecy?'),
      ('Society', false,
       'Is it okay to regift a present you''ll never use?',
       'Czy wolno podarować dalej prezent, którego nigdy nie użyjesz?',
       'Waste nothing?', 'Nic się nie zmarnuje?',
       'Recycling the love?', 'Odgrzewane uczucie?'),
      ('Society', true,
       'Should you spend on a friend''s gift roughly what they spent on yours?',
       'Czy na prezent dla przyjaciela powinieneś wydać tyle, ile on na twój?',
       'Keep it even?', 'Niech będzie równo?',
       'Friendship isn''t math?', 'Przyjaźń to nie matma?'),
      ('Relationships', false,
       'Is it acceptable to cancel plans last minute for a better offer?',
       'Czy wypada odwołać plany w ostatniej chwili dla lepszej oferty?',
       'Live for the moment?', 'Żyj chwilą?',
       'They waited for you?', 'Czekali na ciebie?'),
      ('Family', true,
       'Should newlyweds move in with parents just to save money?',
       'Czy nowożeńcy powinni zamieszkać z rodzicami tylko po to, by oszczędzać?',
       'Smart head start?', 'Mądry start?',
       'No room to grow?', 'Brak miejsca na rozwój?'),
      ('Family', false,
       'Should you side with your partner over your own parents in a fight?',
       'Czy w kłótni powinieneś stanąć po stronie partnera, a nie własnych rodziców?',
       'They''re your family now?', 'Teraz to twoja rodzina?',
       'Blood never changes?', 'Krew się nie zmienia?'),
      ('Family', true,
       'Is it worth marrying someone your family openly disapproves of?',
       'Czy warto poślubić kogoś, kogo twoja rodzina otwarcie nie akceptuje?',
       'Love conquers all?', 'Miłość zwycięża wszystko?',
       'They see what you don''t?', 'Widzą, czego ty nie?'),
      ('Relationships', false,
       'Should the man always be the one to propose?',
       'Czy to zawsze mężczyzna powinien się oświadczać?',
       'Tradition holds?', 'Tradycja trzyma?',
       'Why wait for him?', 'Po co czekać na niego?'),
      ('Family', true,
       'Is it okay for one partner to never work and rely on the other?',
       'Czy wolno, by jedno z partnerów nigdy nie pracowało i żyło na koszt drugiego?',
       'A team divides roles?', 'Drużyna dzieli role?',
       'Too much to carry?', 'Za duży ciężar?'),
      ('Relationships', false,
       'Is moving in together mainly to save money a mistake?',
       'Czy zamieszkanie razem głównie dla oszczędności to błąd?',
       'Practical and smart?', 'Praktycznie i mądrze?',
       'Trapped too soon?', 'Uwięziony za wcześnie?'),
      ('Relationships', true,
       'Should you propose only once you''re financially secure?',
       'Czy powinieneś oświadczyć się dopiero, gdy masz stabilność finansową?',
       'Build the nest first?', 'Najpierw gniazdo?',
       'Love won''t wait?', 'Miłość nie czeka?'),

      -- ---------------- Parenting, childhood & education ----------------
      ('Family', true,
       'Should a parent ever physically punish a misbehaving child?',
       'Czy rodzic powinien kiedykolwiek fizycznie ukarać niegrzeczne dziecko?',
       'A firm hand?', 'Twarda ręka?',
       'Teaching fear?', 'Uczysz strachu?'),
      ('Family', false,
       'Should a child have to say sorry even when they don''t mean it?',
       'Czy dziecko powinno przepraszać, nawet gdy wcale tego nie czuje?',
       'Manners matter?', 'Liczą się maniery?',
       'Empty words?', 'Puste słowa?'),
      ('Family', false,
       'Should you reward a child just for trying, even when they fail?',
       'Czy powinieneś nagradzać dziecko za samą próbę, nawet gdy mu się nie uda?',
       'Effort counts?', 'Liczy się wysiłek?',
       'Winning matters?', 'A wygrana?'),
      ('Family', false,
       'Should you calm a crying child by handing them a screen?',
       'Czy powinieneś uspokajać płaczące dziecko, dając mu ekran?',
       'Sweet silence?', 'Błogi spokój?',
       'Digital pacifier?', 'Cyfrowy smoczek?'),
      ('Family', true,
       'Should a child have to earn screen time by doing chores?',
       'Czy dziecko powinno zasłużyć na czas przed ekranem, wykonując obowiązki?',
       'Screens are earned?', 'Ekran trzeba zasłużyć?',
       'Just let them play?', 'Niech po prostu gra?'),
      ('Family', false,
       'Should a family put all phones away after a set hour at night?',
       'Czy rodzina powinna chować wszystkie telefony po ustalonej godzinie wieczorem?',
       'Sleep first?', 'Najpierw sen?',
       'Whose phone?', 'Czyj telefon?'),
      ('Society', true,
       'Should children start formal schooling as early as possible?',
       'Czy dzieci powinny zaczynać formalną naukę jak najwcześniej?',
       'Head start?', 'Lepszy start?',
       'Let them play?', 'Niech się bawią?'),
      ('Society', true,
       'Should children be taught mainly to pass their exams?',
       'Czy dzieci powinny być uczone głównie pod kątem zdania egzaminów?',
       'Results matter?', 'Liczą się wyniki?',
       'Learning for tests?', 'Nauka pod testy?'),
      ('Society', true,
       'Should failing students be held back to repeat a year?',
       'Czy słabi uczniowie powinni powtarzać rok?',
       'Master it first?', 'Najpierw opanuj?',
       'Branded a failure?', 'Naznaczony porażką?'),
      ('Culture', false,
       'Should every child be made to learn a musical instrument?',
       'Czy każde dziecko powinno uczyć się gry na instrumencie?',
       'Music builds brains?', 'Muzyka rozwija?',
       'Forced art?', 'Sztuka na siłę?'),
      ('Society', false,
       'Should kids be allowed to choose which subjects they study?',
       'Czy dzieci powinny móc same wybierać, których przedmiotów się uczą?',
       'Follow passion?', 'Za pasją?',
       'Too young to know?', 'Za młodzi, by wiedzieć?'),
      ('Society', true,
       'Should children memorize facts they could just look up?',
       'Czy dzieci powinny uczyć się na pamięć faktów, które mogą po prostu sprawdzić?',
       'Train the mind?', 'Ćwicz umysł?',
       'It''s all online?', 'Wszystko jest w sieci?'),
      ('Society', true,
       'Should kids still be taught handwriting in a world of keyboards?',
       'Czy dzieci powinny nadal uczyć się pisma odręcznego w świecie klawiatur?',
       'Keyboards won?', 'Klawiatura wygrała?',
       'A human art?', 'Ludzka sztuka?'),
      ('Family', false,
       'Should you sit with your child every evening until the homework is done?',
       'Czy powinieneś siedzieć z dzieckiem każdego wieczoru, aż skończy pracę domową?',
       'Stay on track?', 'Pilnujesz toku?',
       'Never independent?', 'Nigdy samodzielny?'),
      ('Family', true,
       'Should you compare your child to a more successful sibling?',
       'Czy powinieneś porównywać dziecko do bardziej udanego rodzeństwa?',
       'Sparks drive?', 'Budzi ambicję?',
       'Breeds resentment?', 'Rodzi żal?'),
      ('Family', false,
       'Should you praise a child for being smart rather than for working hard?',
       'Czy powinieneś chwalić dziecko za to, że jest mądre, a nie za ciężką pracę?',
       'Build confidence?', 'Pewność siebie?',
       'Fear of failing?', 'Strach przed porażką?'),
      ('Family', false,
       'Should siblings be treated exactly the same no matter their age?',
       'Czy rodzeństwo powinno być traktowane tak samo, bez względu na wiek?',
       'Fair is fair?', 'Sprawiedliwie?',
       'Age is different?', 'Wiek to wiek?'),
      ('Family', false,
       'Should a teenager be allowed to lock their bedroom door?',
       'Czy nastolatek powinien móc zamykać drzwi swojego pokoju na klucz?',
       'A right to privacy?', 'Prawo do prywatności?',
       'What''s hidden?', 'Co ukrywa?'),
      ('Family', true,
       'Should you let a teenager dress however they want, even if you hate it?',
       'Czy powinieneś pozwolić nastolatkowi ubierać się, jak chce, nawet gdy tego nie znosisz?',
       'Their own style?', 'Własny styl?',
       'You''re judged too?', 'Ciebie też oceniają?'),
      ('Family', false,
       'Should parents follow their teenager on social media?',
       'Czy rodzice powinni obserwować nastolatka w mediach społecznościowych?',
       'Keeping an eye?', 'Masz oko?',
       'Online stalking?', 'Śledzisz w sieci?'),
      ('Family', true,
       'Should a teenager be free to date whoever they choose?',
       'Czy nastolatek powinien móc spotykać się z kim chce?',
       'Their heart?', 'Ich serce?',
       'You know better?', 'Wiesz lepiej?'),
      ('Family', false,
       'Should a child be made to save part of their pocket money?',
       'Czy dziecko powinno być zmuszane do odkładania części kieszonkowego?',
       'Learn to save?', 'Nauka oszczędzania?',
       'Let them enjoy it?', 'Niech się cieszą?'),
      ('Family', true,
       'Should a teenager be expected to earn their own spending money?',
       'Czy nastolatek powinien sam zarabiać na swoje wydatki?',
       'Value of work?', 'Wartość pracy?',
       'Let them be kids?', 'Niech będą dziećmi?'),
      ('Family', false,
       'Should you let a child spend gift money on whatever they want?',
       'Czy powinieneś pozwolić dziecku wydać pieniądze z prezentu na cokolwiek zechce?',
       'Their money?', 'Ich kasa?',
       'A wasted lesson?', 'Stracona lekcja?'),
      ('Family', false,
       'Should boys and girls be given the same chores at home?',
       'Czy chłopcy i dziewczynki powinni dostawać te same obowiązki w domu?',
       'No gender roles?', 'Bez podziału na płeć?',
       'Kids are different?', 'Dzieci są różne?'),
      ('Family', true,
       'Should you force a child to hug relatives they don''t want to?',
       'Czy powinieneś zmuszać dziecko do przytulania krewnych, których nie chce?',
       'Just being polite?', 'Zwykła grzeczność?',
       'Their body, their choice?', 'Ich ciało, ich wybór?'),
      ('Culture', true,
       'Should children be taught to always respect their elders, no matter what?',
       'Czy dzieci powinny być uczone, by zawsze szanować starszych, bez względu na wszystko?',
       'Wisdom of age?', 'Mądrość wieku?',
       'Respect is earned?', 'Szacunek się zarabia?'),
      ('Family', false,
       'Should a child always be made to share their toys?',
       'Czy dziecko zawsze powinno być zmuszane do dzielenia się zabawkami?',
       'Sharing is caring?', 'Dzielić się trzeba?',
       'Some things are mine?', 'Coś jest moje?'),
      ('Family', true,
       'Should you teach a child to fight back against a bully?',
       'Czy powinieneś uczyć dziecko, by oddawało cios dręczycielowi?',
       'Stand your ground?', 'Postaw się?',
       'Violence breeds violence?', 'Przemoc rodzi przemoc?'),
      ('Culture', true,
       'Should you raise your child to share your political views?',
       'Czy powinieneś wychowywać dziecko tak, by podzielało twoje poglądy polityczne?',
       'Pass on values?', 'Przekaż wartości?',
       'Let them think?', 'Niech myślą sami?'),
      ('Family', false,
       'Should you let a boy play with dolls if he wants to?',
       'Czy powinieneś pozwolić chłopcu bawić się lalkami, jeśli ma na to ochotę?',
       'Just a toy?', 'To tylko zabawka?',
       'Mixed signals?', 'Mylne sygnały?'),
      ('Family', true,
       'Should girls and boys be raised in exactly the same way?',
       'Czy dziewczynki i chłopcy powinni być wychowywani dokładnie tak samo?',
       'Equal from birth?', 'Równi od urodzenia?',
       'Born different?', 'Inni od urodzenia?'),
      ('Health', false,
       'Should children have a strict bedtime every single night?',
       'Czy dzieci powinny mieć ścisłą porę snu każdej nocy?',
       'Sleep is sacred?', 'Sen jest święty?',
       'Kill the spontaneity?', 'Zabijasz spontaniczność?'),
      ('Health', false,
       'Should dessert be a reward for finishing the vegetables?',
       'Czy deser powinien być nagrodą za zjedzenie warzyw?',
       'Eat your greens?', 'Zjedz warzywa?',
       'Sweets as a prize?', 'Słodycz jako nagroda?'),
      ('Health', true,
       'Should parents raise their child as a vegetarian?',
       'Czy rodzice powinni wychowywać dziecko na wegetarianina?',
       'Your values?', 'Twoje wartości?',
       'Their choice?', 'Ich wybór?'),
      ('Health', false,
       'Should every child be made to play a team sport?',
       'Czy każde dziecko powinno grać w sport drużynowy?',
       'Learn teamwork?', 'Nauka współpracy?',
       'Not for everyone?', 'Nie dla każdego?'),
      ('Family', true,
       'Should young children specialize in one sport to get ahead?',
       'Czy małe dzieci powinny specjalizować się w jednym sporcie, by wyprzedzić innych?',
       'Raising a champion?', 'Wychowasz mistrza?',
       'One-track life?', 'Życie na jednym torze?'),
      ('Family', false,
       'Should you let a young child walk to school alone?',
       'Czy powinieneś pozwolić małemu dziecku samemu chodzić do szkoły?',
       'Builds independence?', 'Uczy samodzielności?',
       'Too many dangers?', 'Za dużo zagrożeń?'),
      ('Family', true,
       'Should parents watch their kids every second at the playground?',
       'Czy rodzice powinni pilnować dzieci co sekundę na placu zabaw?',
       'Always within reach?', 'Zawsze w zasięgu?',
       'Let them explore?', 'Niech odkrywają?'),
      ('Family', false,
       'Should you let a child take risks like climbing high trees?',
       'Czy powinieneś pozwalać dziecku na ryzyko, jak wspinaczka na wysokie drzewa?',
       'Risk builds grit?', 'Ryzyko hartuje?',
       'One bad fall?', 'Jeden zły upadek?'),
      ('Family', false,
       'Should you tell a child the truth about where babies come from when they ask?',
       'Czy powinieneś mówić dziecku prawdę o tym, skąd się biorą dzieci, gdy pyta?',
       'Honest answers?', 'Szczere odpowiedzi?',
       'Let them be little?', 'Niech będą małe?'),
      ('Family', true,
       'Should a child be told they were adopted?',
       'Czy dziecku należy powiedzieć, że zostało adoptowane?',
       'A right to know?', 'Prawo do prawdy?',
       'Why shake things up?', 'Po co mieszać?'),
      ('Society', false,
       'Should a parent always take the teacher''s side over their child''s?',
       'Czy rodzic powinien zawsze stawać po stronie nauczyciela, a nie dziecka?',
       'Respect authority?', 'Szanuj autorytet?',
       'Whose corner?', 'Po czyjej stronie?'),
      ('Society', true,
       'Should a teacher be allowed to discipline a child without telling the parents?',
       'Czy nauczyciel powinien móc ukarać dziecko bez informowania rodziców?',
       'Handle it in class?', 'Załatw to w klasie?',
       'Parents deserve to know?', 'Rodzice mają wiedzieć?'),
      ('Society', false,
       'Should parents be allowed to challenge the grades a teacher gives?',
       'Czy rodzice powinni móc kwestionować oceny wystawiane przez nauczyciela?',
       'Stand up for your kid?', 'Walcz o dziecko?',
       'Undermining the teacher?', 'Podważasz nauczyciela?'),

      -- ---------------- Money, work, careers & ambition ----------------
      ('Work', false,
       'Should you always have a side hustle, even when your main job pays the bills?',
       'Czy zawsze warto mieć dodatkowe zajęcie, nawet gdy główna praca spina budżet?',
       'More is safer?', 'Więcej znaczy bezpieczniej?',
       'When do you rest?', 'Kiedy odpoczywasz?'),
      ('Work', true,
       'Should you ask for a raise every year, even if no one offered one?',
       'Czy powinieneś prosić o podwyżkę co roku, nawet gdy nikt jej nie proponuje?',
       'Closed mouths starve?', 'Kto nie pyta, ten nie ma?',
       'Pushing your luck?', 'Kusisz los?'),
      ('Money', false,
       'Is it rude to haggle over the price of nearly everything?',
       'Czy to nieuprzejme targować się o cenę prawie wszystkiego?',
       'Nobody pays full?', 'Nikt nie płaci pełnej?',
       'Squeezing the seller?', 'Wyciskasz sprzedawcę?'),
      ('Money', true,
       'Is taking big financial risks the only real path to wealth?',
       'Czy duże finansowe ryzyko to jedyna droga do majątku?',
       'No risk, no riches?', 'Bez ryzyka nie ma zysku?',
       'Slow and safe wins?', 'Wolno i pewnie wygrywa?'),
      ('Work', false,
       'Should you go into business with your best friend?',
       'Czy warto założyć biznes z najlepszym przyjacielem?',
       'Dream team?', 'Wymarzony duet?',
       'Lose both?', 'Stracisz jedno i drugie?'),
      ('Work', true,
       'Is it a mistake to hire your own family?',
       'Czy zatrudnianie własnej rodziny to błąd?',
       'Blood you can trust?', 'Krew, której ufasz?',
       'No firing grandma', 'Babci nie zwolnisz'),
      ('Money', false,
       'Should a group split the bill evenly, even if you barely ordered anything?',
       'Czy grupa powinna dzielić rachunek po równo, nawet gdy ledwo coś zamówiłeś?',
       'Keep it simple?', 'Prościej tak?',
       'Paying for their feast?', 'Płacisz za ich ucztę?'),
      ('Money', true,
       'Should you tell your friends exactly how much you earn?',
       'Czy powinieneś mówić znajomym, ile dokładnie zarabiasz?',
       'Honesty kills taboo?', 'Szczerość zabija tabu?',
       'Breeds envy?', 'Rodzi zazdrość?'),
      ('Money', false,
       'Is it okay to keep a secret savings stash your partner knows nothing about?',
       'Czy w porządku mieć tajne oszczędności, o których partner nie wie?',
       'Your safety net?', 'Twoja poduszka?',
       'Hiding is lying?', 'Ukrywanie to kłamstwo?'),
      ('Society', false,
       'Should you give to charity even when money is tight for you?',
       'Czy powinieneś dawać na cele dobroczynne, nawet gdy u ciebie krucho?',
       'Always someone worse off?', 'Zawsze ktoś ma gorzej?',
       'Help yourself first?', 'Najpierw pomóż sobie?'),
      ('Society', true,
       'Is giving your time to others worth more than giving money?',
       'Czy poświęcanie innym czasu jest warte więcej niż dawanie pieniędzy?',
       'Time is you', 'Czas to ty',
       'Money does more?', 'Pieniądz zdziała więcej?'),
      ('Money', false,
       'Is extreme penny-pinching just greed in disguise?',
       'Czy chorobliwe oszczędzanie to tylko chciwość w przebraniu?',
       'Cheap with everyone?', 'Skąpy dla wszystkich?',
       'Just being smart?', 'Po prostu rozsądek?'),
      ('Money', true,
       'Do the things you own eventually start to own you?',
       'Czy rzeczy, które posiadasz, w końcu zaczynają posiadać ciebie?',
       'More stuff, less freedom?', 'Więcej rzeczy, mniej wolności?',
       'Just enjoy them?', 'Po prostu się ciesz?'),
      ('Work', false,
       'Should you quit the moment a job stops making you happy?',
       'Czy powinieneś odejść, gdy tylko praca przestaje cieszyć?',
       'Life''s too short?', 'Życie za krótkie?',
       'No job is perfect?', 'Żadna praca nie jest idealna?'),
      ('Work', true,
       'Should you stay loyal to a boss who once took a chance on you?',
       'Czy powinieneś być wierny szefowi, który kiedyś dał ci szansę?',
       'Loyalty is earned', 'Lojalność trzeba odwzajemnić',
       'Gratitude won''t pay you', 'Wdzięcznością się nie najesz'),
      ('Money', false,
       'Is it better to retire early with less money than to work longer for more?',
       'Czy lepiej przejść na emeryturę wcześniej z mniejszymi pieniędzmi niż pracować dłużej za większe?',
       'Freedom while young?', 'Wolność, póki młody?',
       'Will it run out?', 'Wystarczy ci?'),
      ('Money', true,
       'Should parents spend their savings on themselves rather than leave it to their children?',
       'Czy rodzice powinni wydać oszczędności na siebie, zamiast zostawiać je dzieciom?',
       'You earned it', 'Zapracowałeś na to',
       'Give them a head start?', 'Dać im fory na start?'),
      ('Money', false,
       'Should parents split their inheritance perfectly equally among all their children?',
       'Czy rodzice powinni podzielić spadek idealnie po równo między wszystkie dzieci?',
       'Fair is equal?', 'Sprawiedliwie znaczy po równo?',
       'Some need more?', 'Jednym trzeba więcej?'),
      ('Money', true,
       'Is buying a luxury item you can barely afford ever worth it?',
       'Czy kupowanie luksusu, na który ledwo cię stać, kiedykolwiek się opłaca?',
       'Treat yourself once?', 'Raz się żyje?',
       'Debt for a logo?', 'Dług za metkę?'),
      ('Money', false,
       'Does an expensive car say more about insecurity than success?',
       'Czy drogie auto mówi więcej o kompleksach niż o sukcesie?',
       'Who are you impressing?', 'Komu chcesz zaimponować?',
       'Or just good taste?', 'Czy po prostu gust?'),
      ('Money', true,
       'Should you always spend less than you earn, no matter what?',
       'Czy zawsze powinieneś wydawać mniej, niż zarabiasz, bez wyjątków?',
       'Golden rule?', 'Złota zasada?',
       'Some moments are worth it', 'Pewne chwile są tego warte'),
      ('Work', false,
       'Is hustle culture doing us more harm than good?',
       'Czy kultura nieustannego zasuwania szkodzi nam bardziej, niż pomaga?',
       'Grind never stops?', 'Zasuwanie bez końca?',
       'Hard work pays?', 'Ciężka praca popłaca?'),
      ('Work', true,
       'Should you feel guilty for resting when you could be working?',
       'Czy powinieneś czuć winę, gdy odpoczywasz, choć mógłbyś pracować?',
       'Rest is earned?', 'Na odpoczynek trzeba zasłużyć?',
       'Rest is a right', 'Odpoczynek to prawo'),
      ('Society', false,
       'Is constant busyness really something to brag about?',
       'Czy ciągłe bycie zajętym to naprawdę powód do dumy?',
       'Proof you matter?', 'Dowód, że się liczysz?',
       'Or just burnout?', 'Czy droga do wypalenia?'),
      ('Work', true,
       'Can you turn your passion into a job without killing the joy of it?',
       'Czy da się zamienić pasję w pracę i nie odebrać jej radości?',
       'Love your work?', 'Kochaj swoją pracę?',
       'Hobby becomes a chore?', 'Hobby staje się obowiązkiem?'),
      ('Work', false,
       'Is freelancing and gig work true freedom?',
       'Czy wolny zawód i dorywcze zlecenia to prawdziwa wolność?',
       'Be your own boss?', 'Sam sobie szefem?',
       'No safety net', 'Zero zabezpieczenia'),
      ('Work', true,
       'Is wanting to get rich a worthy life goal?',
       'Czy chęć wzbogacenia się to godny cel w życiu?',
       'Aim high?', 'Mierz wysoko?',
       'Money isn''t meaning', 'Kasa to nie sens'),
      ('Work', false,
       'Is following your dreams actually bad advice?',
       'Czy podążanie za marzeniami to w gruncie rzeczy zła rada?',
       'Be realistic?', 'Bądź realistą?',
       'Play it safe and regret it?', 'Grasz bezpiecznie i żałujesz?'),
      ('Money', true,
       'Should you tip the same no matter how bad the service was?',
       'Czy powinieneś dać taki sam napiwek bez względu na to, jak słaba była obsługa?',
       'They live on tips?', 'Żyją z napiwków?',
       'Reward bad service?', 'Nagradzasz fuszerkę?'),
      ('Money', false,
       'Is tipping more about guilt than genuine gratitude?',
       'Czy napiwek to bardziej kwestia poczucia winy niż prawdziwej wdzięczności?',
       'Guilt-tipping?', 'Napiwek z winy?',
       'A genuine thank-you', 'Szczere dziękuję'),
      ('Money', true,
       'If you lend money to a friend, should you quietly expect never to see it again?',
       'Jeśli pożyczasz pieniądze przyjacielowi, czy powinieneś z góry założyć, że ich nie odzyskasz?',
       'Treat it as a gift?', 'Traktuj to jak prezent?',
       'A debt is a debt', 'Dług to dług'),
      ('Money', false,
       'Is it always better to give money than to lend it?',
       'Czy zawsze lepiej dać pieniądze, niż je pożyczyć?',
       'Saves the friendship?', 'Ratuje przyjaźń?',
       'Teaches nothing?', 'Niczego nie uczy?'),
      ('Money', true,
       'Is paying in small installments usually a trap?',
       'Czy rozkładanie zakupów na raty to zwykle pułapka?',
       'Buy now, regret later?', 'Kup teraz, żałuj potem?',
       'Spreads the load?', 'Rozkłada ciężar?'),
      ('Money', false,
       'Is it worth going into debt just to keep up with your friends'' lifestyle?',
       'Czy warto wpaść w długi tylko po to, żeby dotrzymać kroku stylowi życia znajomych?',
       'Fit in at any cost?', 'Pasować za wszelką cenę?',
       'Drowning for show?', 'Toniesz dla pokazu?'),
      ('Work', true,
       'Should you move far from everyone you love for a much better job?',
       'Czy powinieneś przeprowadzić się daleko od bliskich dla znacznie lepszej pracy?',
       'Chase the opportunity?', 'Goń za szansą?',
       'Money over people?', 'Kasa ponad ludzi?'),
      ('Work', false,
       'Is success mostly down to hard work rather than luck?',
       'Czy sukces zależy głównie od ciężkiej pracy, a nie od szczęścia?',
       'You make your luck?', 'Sam tworzysz swoje szczęście?',
       'Right place, right time?', 'Dobre miejsce, dobry czas?'),
      ('Work', true,
       'Should you chase every promotion, even when you''re happy where you are?',
       'Czy powinieneś gonić za każdym awansem, nawet gdy jesteś zadowolony tam, gdzie jesteś?',
       'Always climb higher?', 'Zawsze wspinaj się wyżej?',
       'Happy is enough', 'Szczęśliwy to dość'),
      ('Money', false,
       'Is playing it safe with money the biggest risk of all?',
       'Czy granie na bezpiecznie z pieniędzmi to tak naprawdę największe ryzyko?',
       'Safe loses to time?', 'Bezpieczne przegrywa z czasem?',
       'Better than losing it all', 'Lepsze niż stracić wszystko'),
      ('Money', true,
       'Should ordinary people put their savings into risky investments?',
       'Czy zwykli ludzie powinni wkładać oszczędności w ryzykowne inwestycje?',
       'Money should grow?', 'Pieniądz ma rosnąć?',
       'Gambling your future?', 'Hazard z przyszłością?'),
      ('Money', false,
       'Is gambling for fun ever truly harmless?',
       'Czy hazard dla zabawy bywa naprawdę niegroźny?',
       'Just entertainment?', 'Tylko rozrywka?',
       'One bet too many?', 'Jeden zakład za dużo?'),
      ('Work', true,
       'Is quietly doing the bare minimum at a job you dislike ever okay?',
       'Czy robienie po cichu absolutnego minimum w pracy, której nie lubisz, bywa w porządku?',
       'They pay minimum?', 'Płacą minimum?',
       'Stealing your own time?', 'Okradasz sam siebie?'),
      ('Work', false,
       'Is it ever okay to quit a job on the spot, with no notice?',
       'Czy wolno rzucić pracę z dnia na dzień, bez wypowiedzenia?',
       'Owe them nothing?', 'Nic im nie jesteś winien?',
       'Burning the bridge?', 'Palisz za sobą mosty?'),
      ('Money', true,
       'Are you obligated to bail out family who are bad with money?',
       'Czy masz obowiązek ratować rodzinę, która nie radzi sobie z pieniędzmi?',
       'Family is family?', 'Rodzina to rodzina?',
       'Funding bad habits?', 'Finansujesz złe nawyki?'),
      ('Money', false,
       'Is it tacky to talk openly about how much things cost?',
       'Czy to obciach otwarcie mówić, ile co kosztuje?',
       'Just being real?', 'Po prostu szczerość?',
       'Some things stay private', 'Pewne rzeczy zostają prywatne'),
      ('Money', true,
       'Should you always cover the bill for a friend who can''t afford it?',
       'Czy zawsze powinieneś zapłacić rachunek za przyjaciela, którego na to nie stać?',
       'What are friends for?', 'Od czego są przyjaciele?',
       'Charity breeds shame?', 'Jałmużna rodzi wstyd?'),
      ('Work', false,
       'Should you accept the very first salary offer without negotiating?',
       'Czy powinieneś przyjąć pierwszą ofertę pensji bez negocjacji?',
       'Grateful to be picked?', 'Wdzięczny, że wybrali?',
       'Leaving money behind?', 'Zostawiasz kasę na stole?'),

      -- ---------------- Technology, AI, internet & digital life ----------------
      ('Technology', false,
       'Should your social media accounts be deleted forever the moment you die?',
       'Czy twoje konta w social mediach powinny zniknąć na zawsze w chwili twojej śmierci?',
       'A clean ending?', 'Czysty koniec?',
       'Erasing your memory?', 'Wymazujesz pamięć o tobie?'),
      ('Technology', true,
       'Should families be allowed to recreate a dead loved one as a chatbot?',
       'Czy rodziny powinny móc odtworzyć zmarłą bliską osobę jako chatbota?',
       'They never leave?', 'Nigdy nie odchodzą?',
       'Can''t let go?', 'Nie potrafisz puścić?'),
      ('Society', false,
       'Should being an influencer count as a real job?',
       'Czy bycie influencerem powinno liczyć się jako prawdziwa praca?',
       'It pays the bills?', 'Płaci rachunki?',
       'Just showing off?', 'Tylko popisy?'),
      ('Culture', false,
       'Should pro gaming be respected as much as traditional sport?',
       'Czy zawodowy gaming powinien być szanowany tak jak tradycyjny sport?',
       'Skill is skill?', 'Talent to talent?',
       'Where''s the sweat?', 'Gdzie ten pot?'),
      ('Technology', false,
       'Is binge-watching a whole season in one sitting bad for you?',
       'Czy oglądanie całego sezonu na raz jest dla ciebie szkodliwe?',
       'Stealing your sleep?', 'Kradnie ci sen?',
       'Just let me relax?', 'Daj mi odpocząć?'),
      ('Technology', true,
       'Would you spend a week in a virtual world if it felt completely real?',
       'Czy spędziłbyś tydzień w wirtualnym świecie, gdyby wydawał się całkiem prawdziwy?',
       'A perfect escape?', 'Idealna ucieczka?',
       'Running from life?', 'Ucieczka od życia?'),
      ('Technology', true,
       'Should companies have to pay you for using your personal data?',
       'Czy firmy powinny ci płacić za korzystanie z twoich danych?',
       'It''s your gold?', 'To twoje złoto?',
       'Selling yourself?', 'Sprzedajesz siebie?'),
      ('Society', false,
       'Should an old online post be allowed to ruin someone''s life years later?',
       'Czy stary wpis sprzed lat powinien móc zniszczyć komuś życie?',
       'People change?', 'Ludzie się zmieniają?',
       'Words have weight?', 'Słowa mają ciężar?'),
      ('Technology', true,
       'Would you let a device record and play back your dreams?',
       'Czy pozwoliłbyś urządzeniu nagrywać i odtwarzać twoje sny?',
       'See your own mind?', 'Zobaczyć własny umysł?',
       'Nothing stays private?', 'Nic nie zostaje prywatne?'),
      ('Technology', true,
       'Would you let a robot perform your surgery with no doctor in the room?',
       'Czy pozwoliłbyś robotowi operować cię bez lekarza w sali?',
       'Steadier than hands?', 'Pewniejszy niż dłonie?',
       'Who do you blame?', 'Kogo obwinisz?'),
      ('Technology', false,
       'Should a self-driving car be programmed to sacrifice its passenger to save more lives?',
       'Czy auto autonomiczne powinno być zaprogramowane tak, by poświęcić pasażera i ocalić więcej osób?',
       'Math of lives?', 'Matematyka życia?',
       'It should protect me?', 'Ma chronić mnie?'),
      ('Society', false,
       'Is not being able to leave your phone for an hour a real addiction?',
       'Czy nieumiejętność rozstania się z telefonem na godzinę to prawdziwe uzależnienie?',
       'Hooked like a drug?', 'Wciąga jak narkotyk?',
       'Just a habit?', 'Tylko nawyk?'),
      ('Technology', false,
       'Should everyone spend one full day a week with no screens at all?',
       'Czy każdy powinien spędzać jeden dzień w tygodniu zupełnie bez ekranów?',
       'Get your life back?', 'Odzyskać życie?',
       'Who can really unplug?', 'Kto się naprawdę wypnie?'),
      ('Culture', true,
       'Should an AI be allowed to win a creative contest against humans?',
       'Czy AI powinno móc wygrać konkurs twórczy z ludźmi?',
       'Best work wins?', 'Wygrywa najlepsze?',
       'No soul, no prize?', 'Bez duszy, bez nagrody?'),
      ('Technology', true,
       'Would you let an AI make all your money decisions for you?',
       'Czy pozwoliłbyś AI podejmować wszystkie twoje decyzje o pieniądzach?',
       'Cold and smart?', 'Chłodne i mądre?',
       'Trust a machine with it?', 'Zaufać maszynie?'),
      ('Society', false,
       'Is it okay to be rude to a voice assistant or chatbot?',
       'Czy wypada być niegrzecznym dla asystenta głosowego albo chatbota?',
       'It has no feelings?', 'Nie ma uczuć?',
       'Says a lot about you?', 'Mówi sporo o tobie?'),
      ('Technology', false,
       'Should photos that were filtered or edited carry a warning label?',
       'Czy zdjęcia po filtrach albo obróbce powinny mieć ostrzegawczą etykietę?',
       'End fake beauty?', 'Koniec fałszywej urody?',
       'It''s just a photo?', 'To tylko zdjęcie?'),
      ('Society', true,
       'Should making a deepfake of a real person without consent be treated as a crime?',
       'Czy tworzenie deepfake''a prawdziwej osoby bez zgody powinno być traktowane jak przestępstwo?',
       'Stealing your face?', 'Kradzież twojej twarzy?',
       'Where''s the harm?', 'Gdzie tu krzywda?'),
      ('Technology', true,
       'Should infinite-scroll feeds be banned for being designed to addict you?',
       'Czy nieskończone przewijanie powinno być zakazane, bo ma cię uzależniać?',
       'Built to trap you?', 'Stworzone, by wciągać?',
       'Just self-control?', 'Kwestia silnej woli?'),
      ('Technology', false,
       'Should children be banned from games that let strangers chat with them?',
       'Czy dzieci powinny mieć zakaz gier, w których obcy mogą do nich pisać?',
       'Strangers in their room?', 'Obcy w ich pokoju?',
       'Kills the fun?', 'Zabija zabawę?'),
      ('Society', true,
       'Would you feel betrayed if your partner had an AI best friend?',
       'Czy poczułbyś się zdradzony, gdyby twój partner miał najlepszego przyjaciela w AI?',
       'Secrets to a machine?', 'Sekrety dla maszyny?',
       'It''s just an app?', 'To tylko apka?'),
      ('Technology', true,
       'Would you trust an AI''s diagnosis more than a human doctor''s?',
       'Czy ufałbyś diagnozie AI bardziej niż diagnozie lekarza?',
       'It''s read everything?', 'Przeczytało wszystko?',
       'No human eye?', 'Bez ludzkiego oka?'),
      ('Technology', false,
       'Can a friendship that lives only online be as deep as one in person?',
       'Czy przyjaźń, która istnieje tylko w sieci, może być tak głęboka jak ta na żywo?',
       'Closer than neighbors?', 'Bliżej niż sąsiedzi?',
       'Never truly there?', 'Nigdy naprawdę obok?'),
      ('Society', false,
       'Should influencers be forced to admit when their perfect life is staged?',
       'Czy influencerzy powinni mieć obowiązek przyznać, gdy ich idealne życie jest ustawione?',
       'Selling a lie?', 'Sprzedają kłamstwo?',
       'It''s entertainment?', 'To rozrywka?'),
      ('Technology', true,
       'Should kids be allowed to spend real money on surprise rewards in games?',
       'Czy dzieci powinny móc wydawać prawdziwe pieniądze na losowe nagrody w grach?',
       'Gambling for kids?', 'Hazard dla dzieci?',
       'Just their pocket money?', 'To ich kieszonkowe?'),
      ('Society', false,
       'Should children be allowed to earn money as influencers?',
       'Czy dzieci powinny móc zarabiać jako influencerzy?',
       'A childhood on camera?', 'Dzieciństwo przed kamerą?',
       'Let them shine?', 'Niech błyszczą?'),
      ('Technology', true,
       'Should you own everything you ever posted, even after you delete it?',
       'Czy powinieneś być właścicielem wszystkiego, co kiedyś wrzuciłeś, nawet po usunięciu?',
       'It''s yours forever?', 'Na zawsze twoje?',
       'Delete means gone?', 'Usunięte znaczy zniknęło?'),
      ('Society', true,
       'Would you accept being tracked everywhere if it cut crime in half?',
       'Czy zgodziłbyś się na śledzenie wszędzie, gdyby zmniejszyło przestępczość o połowę?',
       'Safer streets?', 'Bezpieczniejsze ulice?',
       'A cage with a view?', 'Klatka z widokiem?'),
      ('Culture', false,
       'Does music written entirely by an AI count as real art?',
       'Czy muzyka napisana w całości przez AI to prawdziwa sztuka?',
       'Sound is sound?', 'Dźwięk to dźwięk?',
       'No heart behind it?', 'Bez serca w środku?'),
      ('Technology', true,
       'Would you let an AI listen to every conversation if it made life easier?',
       'Czy pozwoliłbyś AI słuchać każdej rozmowy, gdyby ułatwiało ci życie?',
       'A perfect helper?', 'Idealny pomocnik?',
       'Always on the record?', 'Wszystko nagrane?'),
      ('Technology', true,
       'Would you upload a skill straight into your brain if you could?',
       'Czy wgrałbyś sobie umiejętność prosto do mózgu, gdybyś mógł?',
       'Master it instantly?', 'Opanować w sekundę?',
       'Earned nothing?', 'Nic nie zapracowane?'),
      ('Society', false,
       'Should phones be banned in schools for the entire day?',
       'Czy telefony powinny być zakazane w szkołach przez cały dzień?',
       'Eyes up, learn more?', 'Głowy w górę, więcej nauki?',
       'A lifeline cut off?', 'Odcięta lina ratunkowa?'),
      ('Society', false,
       'Should people be forgiven online for things they did as teenagers?',
       'Czy ludziom należy w sieci wybaczać to, co zrobili jako nastolatki?',
       'Kids do dumb things?', 'Dzieciaki robią głupoty?',
       'It''s still you?', 'To wciąż ty?'),
      ('Technology', true,
       'Should an AI always have to reveal that it is not a human?',
       'Czy AI zawsze powinno ujawniać, że nie jest człowiekiem?',
       'A right to know?', 'Prawo, by wiedzieć?',
       'Matters if it helps?', 'Ważne, skoro pomaga?'),
      ('Society', false,
       'Is texting slowly killing the art of real conversation?',
       'Czy pisanie wiadomości powoli zabija sztukę prawdziwej rozmowy?',
       'Lost the words?', 'Zgubiliśmy słowa?',
       'Just a new way?', 'Po prostu nowy sposób?'),
      ('Technology', false,
       'Should it be against the rules to buy fake followers and likes?',
       'Czy kupowanie fałszywych obserwujących i lajków powinno być zakazane?',
       'Faking success?', 'Udajesz sukces?',
       'Who does it hurt?', 'Komu to szkodzi?'),
      ('Society', false,
       'Can playing video games be as addictive as a hard drug?',
       'Czy granie w gry może uzależniać jak twardy narkotyk?',
       'Can''t put it down?', 'Nie da się odłożyć?',
       'Just a hobby?', 'Tylko hobby?'),
      ('Technology', true,
       'Would a flawless virtual paradise be a trap rather than a gift?',
       'Czy bezbłędny wirtualny raj byłby raczej pułapką niż darem?',
       'Too good to leave?', 'Za dobre, by wyjść?',
       'Heaven on demand?', 'Niebo na żądanie?'),
      ('Society', false,
       'Should schools replace printed books with tablets completely?',
       'Czy szkoły powinny całkowicie zastąpić papierowe książki tabletami?',
       'The future of learning?', 'Przyszłość nauki?',
       'Yet another screen?', 'Kolejny ekran?'),
      ('Technology', true,
       'Should an AI be allowed to write the news you read?',
       'Czy AI powinno móc pisać wiadomości, które czytasz?',
       'Fast and tireless?', 'Szybkie i niestrudzone?',
       'Who checks the truth?', 'Kto sprawdzi prawdę?'),
      ('Technology', false,
       'In a world full of deepfakes, can you ever fully trust a video again?',
       'Czy w świecie pełnym deepfake''ów da się jeszcze w pełni zaufać nagraniu?',
       'Seeing isn''t believing?', 'Widzieć to nie wierzyć?',
       'Truth leaves traces?', 'Prawda zostawia ślady?'),
      ('Technology', false,
       'Should dating apps be required to verify that every photo is real and recent?',
       'Czy aplikacje randkowe powinny mieć obowiązek sprawdzać, czy każde zdjęcie jest prawdziwe i aktualne?',
       'No more catfish?', 'Koniec z oszustami?',
       'Let people hide?', 'Niech się chowają?'),
      ('Society', false,
       'Is it disrespectful to check your phone while someone is talking to you?',
       'Czy sprawdzanie telefonu, gdy ktoś do ciebie mówi, to brak szacunku?',
       'They feel ignored?', 'Czują się olani?',
       'Everyone does it?', 'Każdy tak robi?'),
      ('Technology', true,
       'Would you put a camera inside your home that streams to a company''s servers?',
       'Czy postawiłbyś w domu kamerę, która transmituje na serwery firmy?',
       'Safer at a glance?', 'Bezpieczniej na oko?',
       'Who''s watching back?', 'Kto patrzy z drugiej strony?'),
      ('Society', false,
       'Is sharing your whole daily life online a harmless habit?',
       'Czy dzielenie się w sieci całym swoim życiem to nieszkodliwy nawyk?',
       'Just connecting?', 'Po prostu więź?',
       'Nothing left private?', 'Nic prywatnego?'),
      ('Technology', true,
       'Does the algorithm know you better than your closest friends do?',
       'Czy algorytm zna cię lepiej niż twoi najbliżsi przyjaciele?',
       'It sees every click?', 'Widzi każde kliknięcie?',
       'It can''t feel you?', 'Nie czuje cię?'),

      -- ---------------- Health, the body, food, the mind & lifestyle ----------------
      ('Health', false,
       'Is it worth counting every calorie you eat?',
       'Czy warto liczyć każdą kalorię, którą zjadasz?',
       'Track it, fix it?', 'Liczysz, panujesz?',
       'Obsession on a plate?', 'Obsesja na talerzu?'),
      ('Health', false,
       'Is breakfast really the most important meal of the day?',
       'Czy śniadanie naprawdę jest najważniejszym posiłkiem dnia?',
       'Fuel to start?', 'Paliwo na start?',
       'Just an old slogan?', 'Stary slogan?'),
      ('Health', true,
       'Are cheat days a smart part of a healthy diet?',
       'Czy dni na luzie to mądra część zdrowej diety?',
       'Sanity needs cake?', 'Głowa chce ciasta?',
       'One day undoes six?', 'Jeden dzień psuje sześć?'),
      ('Health', false,
       'Could you give up sugar completely for the rest of your life?',
       'Czy mógłbyś całkowicie odstawić cukier do końca życia?',
       'Beat the white drug?', 'Pokonać biały proszek?',
       'Life without dessert?', 'Życie bez deseru?'),
      ('Health', false,
       'Is cooking every meal from scratch worth the time it takes?',
       'Czy gotowanie każdego posiłku od zera jest warte czasu, który zżera?',
       'You are what you cook?', 'Jesteś tym, co gotujesz?',
       'Hours you won''t get back', 'Godziny, które nie wrócą'),
      ('Health', false,
       'Is it fine to drink coffee the moment you wake up?',
       'Czy picie kawy zaraz po przebudzeniu to dobry pomysł?',
       'No function without it?', 'Bez niej nie ruszysz?',
       'Spiking on empty?', 'Kofeina na czczo?'),
      ('Health', false,
       'Is eating the same healthy meals every day better than chasing variety?',
       'Czy jedzenie tych samych zdrowych posiłków codziennie jest lepsze niż gonienie za urozmaiceniem?',
       'Boring but winning?', 'Nudne, ale działa?',
       'Food is joy too', 'Jedzenie to też radość'),
      ('Health', false,
       'Should you stop eating the moment you feel full?',
       'Czy powinieneś przestać jeść, gdy tylko poczujesz sytość?',
       'Listen to your body?', 'Słuchaj ciała?',
       'And the last bite?', 'A ten ostatni kęs?'),
      ('Health', true,
       'Do you really need a gym to get in great shape?',
       'Czy naprawdę potrzebujesz siłowni, żeby być w świetnej formie?',
       'Your body is the gym?', 'Ciało to twoja siłownia?',
       'Pay for the push?', 'Płacisz za motywację?'),
      ('Health', false,
       'Is tracking every step and workout taking the joy out of moving?',
       'Czy liczenie każdego kroku i treningu zabija radość z ruchu?',
       'Move for numbers?', 'Ruch dla liczb?',
       'Data drives you?', 'Dane cię napędzają?'),
      ('Health', false,
       'Is no pain, no gain a healthy way to train?',
       'Czy zasada bez bólu nie ma efektów to zdrowe podejście do treningu?',
       'Push past the limit?', 'Przekraczaj granice?',
       'Pain is a warning', 'Ból to ostrzeżenie'),
      ('Health', true,
       'Should rest days matter as much as training days?',
       'Czy dni odpoczynku powinny liczyć się tak samo jak dni treningu?',
       'Rest builds muscle?', 'Odpoczynek buduje mięśnie?',
       'Lazy in disguise?', 'Lenistwo w przebraniu?'),
      ('Health', true,
       'Would you rather be strong than just look strong?',
       'Czy wolałbyś być silny, niż tylko silnie wyglądać?',
       'Function over mirror?', 'Siła ponad lustro?',
       'Looks open doors', 'Wygląd otwiera drzwi'),
      ('Health', false,
       'Is wanting to lose weight ever really about health, not looks?',
       'Czy chęć schudnięcia kiedykolwiek naprawdę chodzi o zdrowie, a nie wygląd?',
       'Be honest with yourself', 'Bądź ze sobą szczery',
       'Looks are health too?', 'Wygląd to też zdrowie?'),
      ('Health', true,
       'Should you weigh yourself every single day?',
       'Czy powinieneś ważyć się każdego dnia?',
       'Know your numbers?', 'Znaj swoje liczby?',
       'A scale runs your mood?', 'Waga rządzi nastrojem?'),
      ('Culture', false,
       'Are beauty filters quietly harming how we see ourselves?',
       'Czy upiększające filtry po cichu psują to, jak widzimy siebie?',
       'Hating the real you?', 'Nie znosisz prawdziwego siebie?',
       'Just a bit of fun?', 'Tylko trochę zabawy?'),
      ('Health', true,
       'Would you freeze your face with injections to look younger?',
       'Czy zamroziłbyś twarz zastrzykami, żeby wyglądać młodziej?',
       'Why look your age?', 'Po co wyglądać na swoje lata?',
       'A frozen smile?', 'Zamrożony uśmiech?'),
      ('Health', false,
       'Is aging gracefully better than fighting it with every tool you have?',
       'Czy starzenie się z godnością jest lepsze niż walka z nim wszelkimi sposobami?',
       'Wrinkles are earned?', 'Zmarszczki się zasługuje?',
       'Why not stay young?', 'Czemu nie zostać młodym?'),
      ('Health', false,
       'Is a daily glass of wine a harmless pleasure?',
       'Czy lampka wina dziennie to niewinna przyjemność?',
       'A little ritual?', 'Mały rytuał?',
       'A habit in disguise?', 'Nałóg w przebraniu?'),
      ('Health', true,
       'Can you truly let loose at a party without drinking?',
       'Czy potrafisz naprawdę wyluzować na imprezie bez alkoholu?',
       'Fun needs no drink?', 'Zabawa bez kieliszka?',
       'Liquid courage?', 'Odwaga z butelki?'),
      ('Health', false,
       'Is being unable to function without caffeine a real problem?',
       'Czy niemożność funkcjonowania bez kofeiny to prawdziwy problem?',
       'Hooked on a cup?', 'Uzależniony od kubka?',
       'Everyone needs a crutch', 'Każdy ma jakąś podporę'),
      ('Health', false,
       'Is the occasional cigarette really that harmful?',
       'Czy okazjonalny papieros jest naprawdę aż tak szkodliwy?',
       'One won''t kill you?', 'Jeden cię nie zabije?',
       'No safe puff?', 'Nie ma bezpiecznego dymka?'),
      ('Health', true,
       'Is sugar as addictive as any hard drug?',
       'Czy cukier uzależnia jak twardy narkotyk?',
       'A legal high?', 'Legalna używka?',
       'It''s just food', 'To tylko jedzenie'),
      ('Health', true,
       'Would you trade an hour of sleep for an hour of free time?',
       'Czy zamieniłbyś godzinę snu na godzinę dla siebie?',
       'Me-time is sacred?', 'Czas dla siebie święty?',
       'Sleep pays it back', 'Sen ci to odda'),
      ('Health', false,
       'Is waking up before dawn the secret to a better life?',
       'Czy wstawanie przed świtem to sekret lepszego życia?',
       'Win the morning?', 'Wygraj poranek?',
       'Night owls thrive too', 'Nocne marki też dają radę'),
      ('Health', false,
       'Is hitting snooze every morning quietly wrecking your day?',
       'Czy klikanie drzemki co rano po cichu rujnuje ci dzień?',
       'Lose before you wake?', 'Przegrywasz przed wstaniem?',
       'Five more minutes?', 'Jeszcze pięć minut?'),
      ('Health', true,
       'Should everyone go to therapy, even with nothing wrong?',
       'Czy każdy powinien chodzić na terapię, nawet gdy nic mu nie dolega?',
       'A check-up for the mind?', 'Przegląd dla głowy?',
       'Fixing what isn''t broken?', 'Naprawiasz, co działa?'),
      ('Health', false,
       'Is talking about your feelings always better than toughing it out?',
       'Czy mówienie o uczuciach zawsze jest lepsze niż zaciskanie zębów?',
       'Let it out?', 'Wyrzuć to z siebie?',
       'Some grit in silence', 'W ciszy też jest siła'),
      ('Culture', false,
       'Is a good-vibes-only attitude bad for your mental health?',
       'Czy nastawienie na same dobre wibracje szkodzi twojej psychice?',
       'Faking the smile?', 'Udajesz uśmiech?',
       'Why drown in the bad?', 'Po co tonąć w złym?'),
      ('Health', true,
       'Would you take a daily pill for longer life if it had side effects?',
       'Czy brałbyś codziennie pigułkę na dłuższe życie, gdyby miała skutki uboczne?',
       'More years, why not?', 'Więcej lat, czemu nie?',
       'A cost you can''t see?', 'Cena, której nie widać?'),
      ('Health', false,
       'Is reaching for a painkiller at the first ache a bad habit?',
       'Czy sięganie po tabletkę przy pierwszym bólu to zły nawyk?',
       'Why suffer for nothing?', 'Po co cierpieć na darmo?',
       'Numbing the signal?', 'Zagłuszasz sygnał?'),
      ('Health', true,
       'Would you want to live to a hundred and fifty if your mind stayed sharp?',
       'Czy chciałbyś dożyć stu pięćdziesięciu lat z bystrym umysłem?',
       'More time to live?', 'Więcej czasu na życie?',
       'Outliving everyone?', 'Przeżyjesz wszystkich?'),
      ('Health', false,
       'Is obsessing over living longer stealing the life you have now?',
       'Czy obsesja na punkcie dłuższego życia kradnie ci życie, które masz teraz?',
       'Living just to live?', 'Żyjesz, by żyć?',
       'Every year counts', 'Każdy rok się liczy'),
      ('Health', true,
       'Are most supplements just a waste of money?',
       'Czy większość suplementów to wyrzucanie pieniędzy?',
       'Pricey urine?', 'Drogi mocz?',
       'Cheap insurance?', 'Tania polisa?'),
      ('Health', true,
       'Is biohacking your body just vanity wearing a lab coat?',
       'Czy biohacking ciała to tylko próżność w kitlu laboratoryjnym?',
       'Optimize everything?', 'Optymalizuj wszystko?',
       'Playing the machine?', 'Bawisz się w maszynę?'),
      ('Health', false,
       'Would you wear a device tracking your body around the clock?',
       'Czy nosiłbyś urządzenie śledzące twoje ciało przez całą dobę?',
       'Know thy body?', 'Poznaj swoje ciało?',
       'Spied on by your wrist?', 'Nadgarstek cię śledzi?'),
      ('Health', true,
       'Is a freezing cold plunge worth the shock for what it gives back?',
       'Czy lodowata kąpiel jest warta szoku za to, co daje w zamian?',
       'Suffer to feel alive?', 'Cierp, by poczuć życie?',
       'Hype in cold water?', 'Moda w zimnej wodzie?'),
      ('Health', false,
       'Is winning the only thing that makes sport worth playing?',
       'Czy wygrywanie to jedyne, co nadaje sportowi sens?',
       'Second is first loser?', 'Drugi to pierwszy przegrany?',
       'The game is the joy', 'Radość jest w grze'),
      ('Health', true,
       'Is it healthier to compete against others than against yourself?',
       'Czy zdrowiej rywalizować z innymi niż z samym sobą?',
       'Rivals make you sharp?', 'Rywale cię ostrzą?',
       'Only you set the bar', 'Poprzeczkę stawiasz sam'),
      ('Culture', false,
       'Should adults keep score even in friendly games?',
       'Czy dorośli powinni liczyć punkty nawet w towarzyskich grach?',
       'Why play to not win?', 'Po co grać, by nie wygrać?',
       'It''s just for fun', 'To tylko dla zabawy'),
      ('Culture', true,
       'Do participation trophies do kids more harm than good?',
       'Czy medale za sam udział szkodzą dzieciom bardziej, niż pomagają?',
       'Everyone''s a winner?', 'Każdy zwycięzcą?',
       'Why crush a child?', 'Po co miażdżyć dziecko?'),
      ('Health', true,
       'Is risking your life for an extreme sport ever worth the thrill?',
       'Czy ryzykowanie życia dla ekstremalnego sportu jest warte tego dreszczyku?',
       'Feel truly alive?', 'Poczuć, że żyjesz?',
       'Worth leaving them?', 'Warte porzucenia bliskich?'),
      ('Health', true,
       'Should you do one thing that scares you every single day?',
       'Czy powinieneś codziennie robić jedną rzecz, która cię przeraża?',
       'Growth lives in fear?', 'Rozwój mieszka w strachu?',
       'Peace is progress too', 'Spokój to też postęp'),
      ('Health', true,
       'Is loving your body as it is just an excuse to stop trying?',
       'Czy kochanie ciała takim, jakie jest, to tylko wymówka, by przestać próbować?',
       'Settling for less?', 'Godzisz się na mniej?',
       'Peace isn''t quitting', 'Akceptacja to nie kapitulacja'),
      ('Health', false,
       'Is a certain amount of stress actually good for you?',
       'Czy pewna dawka stresu jest dla ciebie naprawdę dobra?',
       'Pressure sharpens you?', 'Presja cię wyostrza?',
       'Slow poison?', 'Powolna trucizna?'),

      -- ---------------- Ethics, justice, society, freedom, animals & meaning ----------------
      ('Society', false,
       'Is anonymous giving, where no one ever knows you helped, more virtuous than public charity?',
       'Czy anonimowe dawanie, gdy nikt nie wie, że pomogłeś, jest szlachetniejsze niż jawna dobroczynność?',
       'No applause needed?', 'Bez braw?',
       'Why hide good?', 'Po co kryć dobro?'),
      ('Ethics', true,
       'Does doing good only truly count when it costs you something?',
       'Czy dobry uczynek liczy się naprawdę tylko wtedy, gdy cię coś kosztuje?',
       'Sacrifice is the proof?', 'Poświęcenie to dowód?',
       'Good is still good?', 'Dobro to wciąż dobro?'),
      ('Society', false,
       'Is it wrong to give to charity mainly for the recognition?',
       'Czy to złe dawać na cele dobroczynne głównie dla poklasku?',
       'Help is help?', 'Pomoc to pomoc?',
       'Buying applause?', 'Kupujesz oklaski?'),
      ('Society', false,
       'Should you give to others until it genuinely hurts your own life?',
       'Czy powinieneś dawać innym aż do momentu, gdy naprawdę odbija się to na twoim życiu?',
       'Owe the world more?', 'Winny światu więcej?',
       'Save yourself first?', 'Najpierw ratuj siebie?'),
      ('Ethics', true,
       'Is it wrong to live in comfort while strangers somewhere go hungry?',
       'Czy to złe żyć w dostatku, gdy gdzieś obcy ludzie głodują?',
       'Guilt at the table?', 'Wina przy stole?',
       'You earned your plate?', 'Zasłużyłeś na swój talerz?'),
      ('Freedom', false,
       'Is it right to break a rule you believe is deeply unjust?',
       'Czy słusznie jest złamać zasadę, którą uważasz za głęboko niesprawiedliwą?',
       'Conscience over order?', 'Sumienie ponad nakaz?',
       'Rules hold us together?', 'Zasady nas spajają?'),
      ('Justice', true,
       'If those meant to deliver justice fail, should you take it into your own hands?',
       'Jeśli ci, którzy mają wymierzać sprawiedliwość, zawodzą, czy powinieneś wziąć ją we własne ręce?',
       'Wait forever?', 'Czekać bez końca?',
       'Then who judges you?', 'To kto osądzi ciebie?'),
      ('Justice', false,
       'Should why someone did wrong matter as much as what they actually did?',
       'Czy to, dlaczego ktoś postąpił źle, powinno ważyć tyle samo co sam czyn?',
       'The story behind it?', 'Co kryje się za tym?',
       'A wrong is a wrong?', 'Zło to zło?'),
      ('Justice', true,
       'Is punishment really just revenge wearing a nicer mask?',
       'Czy kara to tak naprawdę tylko zemsta w ładniejszej masce?',
       'Payback in a suit?', 'Zemsta w garniturze?',
       'It keeps order?', 'Trzyma porządek?'),
      ('Justice', false,
       'Can any punishment ever truly undo the harm that was done?',
       'Czy jakakolwiek kara jest w stanie naprawdę cofnąć wyrządzoną krzywdę?',
       'Balance the scales?', 'Wyrównać szale?',
       'The damage stays?', 'Szkoda zostaje?'),
      ('Ethics', false,
       'Is forgiving someone a sign of strength rather than weakness?',
       'Czy wybaczenie to oznaka siły, a nie słabości?',
       'Letting go is power?', 'Odpuścić to siła?',
       'Letting them win?', 'Pozwalasz im wygrać?'),
      ('Justice', true,
       'Should forgiveness have to be earned rather than freely given?',
       'Czy na wybaczenie trzeba zasłużyć, zamiast dostać je za darmo?',
       'Earn your way back?', 'Zasłuż na powrót?',
       'Grace asks nothing?', 'Łaska nic nie żąda?'),
      ('Ethics', false,
       'Can you ever truly forgive someone without forgetting what they did?',
       'Czy da się komuś naprawdę wybaczyć, nie zapominając, co zrobił?',
       'The heart remembers?', 'Serce pamięta?',
       'Real mercy forgets?', 'Prawdziwa litość zapomina?'),
      ('Ethics', true,
       'Should you forgive yourself for a mistake that hurt someone else?',
       'Czy powinieneś wybaczyć sobie błąd, który zranił kogoś innego?',
       'Carry it forever?', 'Nieść to wiecznie?',
       'Who lets you off?', 'Kto cię rozgrzeszy?'),
      ('Society', false,
       'Is going along with the crowd to keep the peace a quiet betrayal of yourself?',
       'Czy płynięcie z tłumem dla świętego spokoju to cicha zdrada samego siebie?',
       'Sold out to fit in?', 'Sprzedać się, by pasować?',
       'Pick your battles?', 'Wybieraj bitwy?'),
      ('Freedom', false,
       'Is it better to be fully yourself than to be liked by everyone?',
       'Czy lepiej być w pełni sobą niż lubianym przez wszystkich?',
       'Belong or be real?', 'Pasować czy być sobą?',
       'Lonely being you?', 'Samotny ze sobą?'),
      ('Society', true,
       'Should you speak up against the group even when it could cost you everything?',
       'Czy powinieneś sprzeciwić się grupie, nawet gdy może cię to kosztować wszystko?',
       'Stand alone?', 'Stanąć samemu?',
       'Some fights aren''t yours?', 'Nie każda walka twoja?'),
      ('Freedom', false,
       'Is a safe and comfortable life secretly a wasted one?',
       'Czy bezpieczne i wygodne życie to po cichu życie zmarnowane?',
       'Comfort is a cage?', 'Wygoda to klatka?',
       'Peace is the point?', 'Spokój to cel?'),
      ('Ethics', false,
       'Should you always choose the harder right over the easier wrong?',
       'Czy zawsze powinieneś wybierać trudniejsze dobro zamiast łatwiejszego zła?',
       'Take the easy way?', 'Pójść na łatwiznę?',
       'Always? Really?', 'Zawsze? Serio?'),
      ('Society', true,
       'Is avoiding a fight you could win for what''s right an act of cowardice?',
       'Czy unikanie walki o słuszną sprawę, którą mógłbyś wygrać, to tchórzostwo?',
       'Silence is comfort?', 'Cisza to wygoda?',
       'Wisdom to step back?', 'Mądrość to odpuścić?'),
      ('Ethics', false,
       'Do good results excuse the bad methods used to reach them?',
       'Czy dobre rezultaty usprawiedliwiają złe metody, którymi je osiągnięto?',
       'Ends over means?', 'Cel ponad środki?',
       'Rotten at the root?', 'Zgniłe u korzenia?'),
      ('Ethics', true,
       'Is it acceptable to commit a small wrong to achieve a great good?',
       'Czy wolno popełnić małe zło, by osiągnąć wielkie dobro?',
       'Just a little sin?', 'Tylko mały grzech?',
       'Where does it stop?', 'Gdzie się to kończy?'),
      ('Ethics', false,
       'Should you cover for a friend who clearly did something wrong?',
       'Czy powinieneś kryć przyjaciela, który ewidentnie zrobił coś złego?',
       'Loyalty first?', 'Lojalność najpierw?',
       'Now you''re in it too?', 'Teraz ty też w to wchodzisz?'),
      ('Justice', true,
       'Is loyalty still a virtue when it shields someone who is guilty?',
       'Czy lojalność wciąż jest cnotą, gdy osłania winnego?',
       'Stand by your own?', 'Trzymać ze swoimi?',
       'Blind to the harm?', 'Ślepy na krzywdę?'),
      ('Society', false,
       'Can helping someone too much end up doing them harm?',
       'Czy pomaganie komuś za bardzo może w końcu mu zaszkodzić?',
       'Crutch or cure?', 'Kula czy lekarstwo?',
       'Kindness has no limit?', 'Dobroć nie ma granic?'),
      ('Society', false,
       'Should you always give a stranger the benefit of the doubt?',
       'Czy zawsze powinieneś zakładać u obcego dobre intencje?',
       'Assume the best?', 'Zakładać najlepsze?',
       'Until you''re burned?', 'Aż cię oparzą?'),
      ('Ethics', true,
       'Deep down, does everyone act mainly out of self-interest?',
       'Czy w głębi duszy każdy działa głównie z własnego interesu?',
       'No truly selfless act?', 'Nie ma bezinteresowności?',
       'Some give freely?', 'Niektórzy dają z serca?'),
      ('Ethics', true,
       'Is being selfish sometimes exactly the right thing to do?',
       'Czy bycie egoistą bywa czasem dokładnie tym, co należy zrobić?',
       'Put yourself first?', 'Postaw siebie na pierwszym miejscu?',
       'At whose cost?', 'Czyim kosztem?'),
      ('Environment', false,
       'Should you give up eating meat for the planet, even if you love it?',
       'Czy powinieneś zrezygnować z mięsa dla planety, nawet jeśli je uwielbiasz?',
       'Taste vs the Earth?', 'Smak kontra Ziemia?',
       'One plate won''t save it?', 'Jeden talerz nie ocali?'),
      ('Environment', true,
       'Is it wrong to own far more than you could ever need?',
       'Czy to złe mieć o wiele więcej, niż kiedykolwiek mógłbyś potrzebować?',
       'Hoarding while others lack?', 'Gromadzisz, gdy innym brak?',
       'You earned every bit?', 'Zarobiłeś na każdy grosz?'),
      ('Environment', false,
       'Is buying something new always worse for the planet than repairing the old?',
       'Czy kupno nowej rzeczy jest dla planety zawsze gorsze niż naprawa starej?',
       'A throwaway world?', 'Świat na wyrzucenie?',
       'Sometimes new is greener?', 'Czasem nowe jest czystsze?'),
      ('Environment', true,
       'Given the state of the world, is it fair to bring a new child into it?',
       'Czy w obecnym stanie świata sprowadzanie na niego nowego dziecka jest w porządku?',
       'A hard world ahead?', 'Trudny świat przed nim?',
       'Hope is born too?', 'Z nim rodzi się nadzieja?'),
      ('Environment', false,
       'Is it selfish to keep a pet alone in a small home all day?',
       'Czy to egoistyczne trzymać zwierzaka samego w małym mieszkaniu cały dzień?',
       'A life in a box?', 'Życie w pudełku?',
       'Being loved is enough?', 'Bycie kochanym wystarczy?'),
      ('Ethics', true,
       'Does an animal''s suffering deserve the same weight as a human''s?',
       'Czy cierpienie zwierzęcia zasługuje na tę samą wagę co ludzkie?',
       'Pain is pain?', 'Ból to ból?',
       'People come first?', 'Ludzie najpierw?'),
      ('Ethics', true,
       'Is it wrong to spend a fortune on a pet''s surgery while people go without?',
       'Czy to złe wydać fortunę na operację zwierzaka, gdy ludziom brakuje na życie?',
       'Family is family?', 'Rodzina to rodzina?',
       'A life is a life?', 'Życie to życie?'),
      ('Society', false,
       'Is it wrong to breed new pets while shelters stay full?',
       'Czy to złe rozmnażać nowe zwierzęta, gdy schroniska są pełne?',
       'Empty the shelters first?', 'Najpierw opróżnij schroniska?',
       'Free to choose?', 'Wolny wybór?'),
      ('Ethics', true,
       'Is ending a suffering pet''s life an act of love?',
       'Czy zakończenie cierpienia zwierzaka to akt miłości?',
       'Mercy over your pain?', 'Litość ponad twój ból?',
       'Who says it''s time?', 'Kto mówi, że już czas?'),
      ('Culture', false,
       'Does it really matter how you are remembered once you are gone?',
       'Czy naprawdę ma znaczenie, jak cię zapamiętają, gdy już cię nie będzie?',
       'Your name lives on?', 'Imię żyje dalej?',
       'You won''t be there?', 'Ciebie już nie będzie?'),
      ('Culture', true,
       'Is wanting to be remembered after death just vanity?',
       'Czy pragnienie bycia pamiętanym po śmierci to tylko próżność?',
       'Chasing your own statue?', 'Gonisz własny pomnik?',
       'A mark worth leaving?', 'Ślad wart zostawienia?'),
      ('Society', false,
       'Is a quiet, ordinary life just as worthy as an extraordinary one?',
       'Czy ciche, zwyczajne życie jest tak samo wartościowe jak to niezwykłe?',
       'A small life, a full life?', 'Małe życie, pełne życie?',
       'Wasting your shot?', 'Marnujesz swoją szansę?'),
      ('Culture', true,
       'Is a life of comfort and pleasure less meaningful than one of struggle and purpose?',
       'Czy życie w wygodzie i przyjemności ma mniej sensu niż życie w trudzie i celu?',
       'No pain, no meaning?', 'Bez bólu nie ma sensu?',
       'Is joy not enough?', 'Radość nie wystarczy?'),
      ('Society', false,
       'Is the fear of death the very thing that makes life precious?',
       'Czy to właśnie strach przed śmiercią czyni życie cennym?',
       'No end, no value?', 'Bez końca nie ma wartości?',
       'Fear just steals joy?', 'Strach tylko kradnie radość?'),
      ('Society', false,
       'Should children be told the plain truth about death?',
       'Czy dzieciom należy mówić wprost prawdę o śmierci?',
       'They can handle it?', 'Udźwigną to?',
       'Let them stay children?', 'Niech zostaną dziećmi?'),
      ('Freedom', true,
       'Can a person be truly good without believing in anything greater than themselves?',
       'Czy człowiek może być naprawdę dobry, nie wierząc w nic większego od siebie?',
       'Goodness needs no heaven?', 'Dobro nie potrzebuje nieba?',
       'What anchors right?', 'Co kotwiczy dobro?'),
      ('Society', true,
       'Does a meaningful life require believing in something bigger than yourself?',
       'Czy sensowne życie wymaga wiary w coś większego od siebie?',
       'Need a higher why?', 'Trzeba wyższego po co?',
       'You make your own meaning?', 'Sens tworzysz sam?'),
      ('Society', false,
       'Should you feel grateful for the hardships that shaped who you are?',
       'Czy powinieneś być wdzięczny za trudy, które ukształtowały to, kim jesteś?',
       'Thank the pain?', 'Dziękować bólowi?',
       'It still took from you?', 'I tak ci zabrało?'),

      -- ---------------- A few more global etiquette / lifestyle dilemmas ----------------
      ('Culture', false,
       'Is it rude to arrive at someone''s home empty-handed?',
       'Czy to nieuprzejme przyjść do kogoś z pustymi rękami?',
       'Just bring yourself?', 'Wystarczysz ty sam?',
       'Always bring something?', 'Zawsze coś przynieś?'),
      ('Culture', false,
       'Should you finish a book you''ve started even when you hate it?',
       'Czy powinieneś dokończyć zaczętą książkę, nawet gdy jej nie znosisz?',
       'Push through?', 'Przebrnij?',
       'Life''s too short?', 'Życie za krótkie?'),
      ('Society', true,
       'Is it wrong to recline your seat all the way on a long journey?',
       'Czy to złe odchylić oparcie do końca podczas długiej podróży?',
       'Your seat, your right?', 'Twoje miejsce, twoje prawo?',
       'And the person behind?', 'A ten za tobą?')
    ) as s(category, is_premium, en, pl, a1en, a1pl, a2en, a2pl)
  loop
    -- skip if this EN text was already seeded
    if exists (
      select 1 from public.question_translations
      where locale = 'en' and question_text = r.en
    ) then
      continue;
    end if;

    insert into public.questions (category, is_premium)
    values (r.category, r.is_premium)
    returning id into qid;

    insert into public.question_translations (question_id, locale, question_text)
    values (qid, 'en', r.en),
           (qid, 'pl', r.pl);

    -- smaczek 1 (free teaser)
    insert into public.question_smaczki (question_id, position, is_active)
    values (qid, 1, true)
    returning id into s1;
    insert into public.question_smaczki_translations (smaczek_id, locale, text)
    values (s1, 'en', r.a1en),
           (s1, 'pl', r.a1pl);

    -- smaczek 2 (premium)
    insert into public.question_smaczki (question_id, position, is_active)
    values (qid, 2, true)
    returning id into s2;
    insert into public.question_smaczki_translations (smaczek_id, locale, text)
    values (s2, 'en', r.a2en),
           (s2, 'pl', r.a2pl);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- 2) Schedule every still-unscheduled active question onto the next free dates.
--    Keeps Strategy A (unique question_id) intact. Wide horizon so the whole
--    new batch lands on a calendar slot.
-- ----------------------------------------------------------------------------
insert into public.daily_questions (publish_date, question_id)
select dates.d::date, q.id
from (
  select d, row_number() over (order by d) rn
  from generate_series(current_date, current_date + 1999, '1 day'::interval) d
  where d::date not in (select publish_date from public.daily_questions)
) dates
join (
  select id, row_number() over (order by random()) rn
  from public.questions
  where is_active
    and id not in (select question_id from public.daily_questions)
) q on q.rn = dates.rn
on conflict do nothing;

commit;
